version: '2'
services:
  node:
    container_name: wfnetworth_nodejs
    build: ./docker/node
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www/app
    networks:
      - wfnetworth_net
    depends_on:
     - db
  db:
    container_name: wfnetworth_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wfnetworth
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
     - db_data:/var/lib/mysql
    networks:
     - wfnetworth_net
networks:
  wfnetworth_net:
    driver: "bridge"
volumes:
  db_data:
    driver: "local"
